package demo.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table almn_comment
 */
public class AlmnComment extends BaseModel {

	/**
	 * 动态ID
	 * @ColumnNamedailys_id
	 * @mbg.generated   2021-04-22 13:25:30
	 */
	private String dailysId;
	/**
	 * 被评论/回复id
	 * @ColumnNamecomment1_id
	 * @mbg.generated   2021-04-22 13:25:30
	 */
	private String comment1Id;
	/**
	 * 评论id
	 * @ColumnNamecomment2_id
	 * @mbg.generated   2021-04-22 13:25:30
	 */
	private String comment2Id;
	/**
	 * 评论内容
	 * @ColumnNamecomment_content
	 * @mbg.generated   2021-04-22 13:25:30
	 */
	private String commentContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_comment.dailys_id
	 * @return  the value of almn_comment.dailys_id
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	public String getDailysId() {
		return dailysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_comment.dailys_id
	 * @param dailysId  the value for almn_comment.dailys_id
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	public void setDailysId(String dailysId) {
		this.dailysId = dailysId == null ? null : dailysId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_comment.comment1_id
	 * @return  the value of almn_comment.comment1_id
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	public String getComment1Id() {
		return comment1Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_comment.comment1_id
	 * @param comment1Id  the value for almn_comment.comment1_id
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	public void setComment1Id(String comment1Id) {
		this.comment1Id = comment1Id == null ? null : comment1Id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_comment.comment2_id
	 * @return  the value of almn_comment.comment2_id
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	public String getComment2Id() {
		return comment2Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_comment.comment2_id
	 * @param comment2Id  the value for almn_comment.comment2_id
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	public void setComment2Id(String comment2Id) {
		this.comment2Id = comment2Id == null ? null : comment2Id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_comment.comment_content
	 * @return  the value of almn_comment.comment_content
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	public String getCommentContent() {
		return commentContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_comment.comment_content
	 * @param commentContent  the value for almn_comment.comment_content
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent == null ? null : commentContent.trim();
	}
}