package demo.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table almn_daily
 */
public class AlmnDaily extends BaseModel {
    /**
	 * 发布动态用户学号
	 * @ColumnNameuser_id
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private String userId;
	/**
	 * 动态ID
	 * @ColumnNamedaily_id
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private String dailyId;
	/**
	 * 动态标签1
	 * @ColumnNamedaily_tag1
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private String dailyTag1;
	/**
	 * 动态标签2
	 * @ColumnNamedaily_tag2
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private String dailyTag2;
	/**
	 * 动态内容
	 * @ColumnNamedaily_content
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private String dailyContent;
	/**
	 * 动态图片列表
	 * @ColumnNamedaily_img_list
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private String dailyImgList;
	/**
	 * 点赞数
	 * @ColumnNamefavor_cnt
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private Integer favorCnt;
	/**
	 * 投币数
	 * @ColumnNamecoin_cnt
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private Integer coinCnt;
	/**
	 * 好评数
	 * @ColumnNamepraise_cnt
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private Integer praiseCnt;
	/**
	 * 差评数
	 * @ColumnNamenegative_cnt
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private Integer negativeCnt;
	/**
	 * 普通评论数
	 * @ColumnNameavg_cnt
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private Integer avgCnt;
	/**
	 * 热度/影响力
	 * @ColumnNameeffect_cnt
	 * @mbg.generated   2021-05-30 11:06:56
	 */
	private Integer effectCnt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.user_id
	 * @return  the value of almn_daily.user_id
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.user_id
	 * @param userId  the value for almn_daily.user_id
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.daily_id
	 * @return  the value of almn_daily.daily_id
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public String getDailyId() {
		return dailyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.daily_id
	 * @param dailyId  the value for almn_daily.daily_id
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setDailyId(String dailyId) {
		this.dailyId = dailyId == null ? null : dailyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.daily_tag1
	 * @return  the value of almn_daily.daily_tag1
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public String getDailyTag1() {
		return dailyTag1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.daily_tag1
	 * @param dailyTag1  the value for almn_daily.daily_tag1
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setDailyTag1(String dailyTag1) {
		this.dailyTag1 = dailyTag1 == null ? null : dailyTag1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.daily_tag2
	 * @return  the value of almn_daily.daily_tag2
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public String getDailyTag2() {
		return dailyTag2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.daily_tag2
	 * @param dailyTag2  the value for almn_daily.daily_tag2
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setDailyTag2(String dailyTag2) {
		this.dailyTag2 = dailyTag2 == null ? null : dailyTag2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.daily_content
	 * @return  the value of almn_daily.daily_content
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public String getDailyContent() {
		return dailyContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.daily_content
	 * @param dailyContent  the value for almn_daily.daily_content
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setDailyContent(String dailyContent) {
		this.dailyContent = dailyContent == null ? null : dailyContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.daily_img_list
	 * @return  the value of almn_daily.daily_img_list
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public String getDailyImgList() {
		return dailyImgList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.daily_img_list
	 * @param dailyImgList  the value for almn_daily.daily_img_list
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setDailyImgList(String dailyImgList) {
		this.dailyImgList = dailyImgList == null ? null : dailyImgList.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.favor_cnt
	 * @return  the value of almn_daily.favor_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public Integer getFavorCnt() {
		return favorCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.favor_cnt
	 * @param favorCnt  the value for almn_daily.favor_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setFavorCnt(Integer favorCnt) {
		this.favorCnt = favorCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.coin_cnt
	 * @return  the value of almn_daily.coin_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public Integer getCoinCnt() {
		return coinCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.coin_cnt
	 * @param coinCnt  the value for almn_daily.coin_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setCoinCnt(Integer coinCnt) {
		this.coinCnt = coinCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.praise_cnt
	 * @return  the value of almn_daily.praise_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public Integer getPraiseCnt() {
		return praiseCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.praise_cnt
	 * @param praiseCnt  the value for almn_daily.praise_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setPraiseCnt(Integer praiseCnt) {
		this.praiseCnt = praiseCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.negative_cnt
	 * @return  the value of almn_daily.negative_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public Integer getNegativeCnt() {
		return negativeCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.negative_cnt
	 * @param negativeCnt  the value for almn_daily.negative_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setNegativeCnt(Integer negativeCnt) {
		this.negativeCnt = negativeCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.avg_cnt
	 * @return  the value of almn_daily.avg_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public Integer getAvgCnt() {
		return avgCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.avg_cnt
	 * @param avgCnt  the value for almn_daily.avg_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setAvgCnt(Integer avgCnt) {
		this.avgCnt = avgCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_daily.effect_cnt
	 * @return  the value of almn_daily.effect_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public Integer getEffectCnt() {
		return effectCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_daily.effect_cnt
	 * @param effectCnt  the value for almn_daily.effect_cnt
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setEffectCnt(Integer effectCnt) {
		this.effectCnt = effectCnt;
	}

	@Override
	public String toString() {
		return "AlmnDaily [userId=" + userId + ", dailyId=" + dailyId + ", dailyContent=" + dailyContent
				+ ", dailyImgList=" + dailyImgList + ", favorCnt=" + favorCnt + ", coinCnt=" + coinCnt + ", praiseCnt="
				+ praiseCnt + ", negativeCnt=" + negativeCnt + ", avgCnt=" + avgCnt + ", effectCnt=" + effectCnt
				+ ", toString()=" + super.toString() + "]";
	}
    
}