package demo.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AlmnUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public AlmnUserExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNull() {
			addCriterion("role_id is null");
			return (Criteria) this;
		}

		public Criteria andRoleIdIsNotNull() {
			addCriterion("role_id is not null");
			return (Criteria) this;
		}

		public Criteria andRoleIdEqualTo(Integer value) {
			addCriterion("role_id =", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotEqualTo(Integer value) {
			addCriterion("role_id <>", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThan(Integer value) {
			addCriterion("role_id >", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("role_id >=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThan(Integer value) {
			addCriterion("role_id <", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
			addCriterion("role_id <=", value, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdIn(List<Integer> values) {
			addCriterion("role_id in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotIn(List<Integer> values) {
			addCriterion("role_id not in", values, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdBetween(Integer value1, Integer value2) {
			addCriterion("role_id between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("role_id not between", value1, value2, "roleId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserIsNull() {
			addCriterion("enjoy_user is null");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserIsNotNull() {
			addCriterion("enjoy_user is not null");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserEqualTo(String value) {
			addCriterion("enjoy_user =", value, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserNotEqualTo(String value) {
			addCriterion("enjoy_user <>", value, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserGreaterThan(String value) {
			addCriterion("enjoy_user >", value, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserGreaterThanOrEqualTo(String value) {
			addCriterion("enjoy_user >=", value, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserLessThan(String value) {
			addCriterion("enjoy_user <", value, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserLessThanOrEqualTo(String value) {
			addCriterion("enjoy_user <=", value, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserLike(String value) {
			addCriterion("enjoy_user like", value, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserNotLike(String value) {
			addCriterion("enjoy_user not like", value, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserIn(List<String> values) {
			addCriterion("enjoy_user in", values, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserNotIn(List<String> values) {
			addCriterion("enjoy_user not in", values, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserBetween(String value1, String value2) {
			addCriterion("enjoy_user between", value1, value2, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyUserNotBetween(String value1, String value2) {
			addCriterion("enjoy_user not between", value1, value2, "enjoyUser");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagIsNull() {
			addCriterion("enjoy_tag is null");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagIsNotNull() {
			addCriterion("enjoy_tag is not null");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagEqualTo(String value) {
			addCriterion("enjoy_tag =", value, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagNotEqualTo(String value) {
			addCriterion("enjoy_tag <>", value, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagGreaterThan(String value) {
			addCriterion("enjoy_tag >", value, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagGreaterThanOrEqualTo(String value) {
			addCriterion("enjoy_tag >=", value, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagLessThan(String value) {
			addCriterion("enjoy_tag <", value, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagLessThanOrEqualTo(String value) {
			addCriterion("enjoy_tag <=", value, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagLike(String value) {
			addCriterion("enjoy_tag like", value, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagNotLike(String value) {
			addCriterion("enjoy_tag not like", value, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagIn(List<String> values) {
			addCriterion("enjoy_tag in", values, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagNotIn(List<String> values) {
			addCriterion("enjoy_tag not in", values, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagBetween(String value1, String value2) {
			addCriterion("enjoy_tag between", value1, value2, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andEnjoyTagNotBetween(String value1, String value2) {
			addCriterion("enjoy_tag not between", value1, value2, "enjoyTag");
			return (Criteria) this;
		}

		public Criteria andUserPasswdIsNull() {
			addCriterion("user_passwd is null");
			return (Criteria) this;
		}

		public Criteria andUserPasswdIsNotNull() {
			addCriterion("user_passwd is not null");
			return (Criteria) this;
		}

		public Criteria andUserPasswdEqualTo(String value) {
			addCriterion("user_passwd =", value, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdNotEqualTo(String value) {
			addCriterion("user_passwd <>", value, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdGreaterThan(String value) {
			addCriterion("user_passwd >", value, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdGreaterThanOrEqualTo(String value) {
			addCriterion("user_passwd >=", value, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdLessThan(String value) {
			addCriterion("user_passwd <", value, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdLessThanOrEqualTo(String value) {
			addCriterion("user_passwd <=", value, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdLike(String value) {
			addCriterion("user_passwd like", value, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdNotLike(String value) {
			addCriterion("user_passwd not like", value, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdIn(List<String> values) {
			addCriterion("user_passwd in", values, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdNotIn(List<String> values) {
			addCriterion("user_passwd not in", values, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdBetween(String value1, String value2) {
			addCriterion("user_passwd between", value1, value2, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserPasswdNotBetween(String value1, String value2) {
			addCriterion("user_passwd not between", value1, value2, "userPasswd");
			return (Criteria) this;
		}

		public Criteria andUserIconIsNull() {
			addCriterion("user_icon is null");
			return (Criteria) this;
		}

		public Criteria andUserIconIsNotNull() {
			addCriterion("user_icon is not null");
			return (Criteria) this;
		}

		public Criteria andUserIconEqualTo(String value) {
			addCriterion("user_icon =", value, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconNotEqualTo(String value) {
			addCriterion("user_icon <>", value, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconGreaterThan(String value) {
			addCriterion("user_icon >", value, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconGreaterThanOrEqualTo(String value) {
			addCriterion("user_icon >=", value, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconLessThan(String value) {
			addCriterion("user_icon <", value, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconLessThanOrEqualTo(String value) {
			addCriterion("user_icon <=", value, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconLike(String value) {
			addCriterion("user_icon like", value, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconNotLike(String value) {
			addCriterion("user_icon not like", value, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconIn(List<String> values) {
			addCriterion("user_icon in", values, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconNotIn(List<String> values) {
			addCriterion("user_icon not in", values, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconBetween(String value1, String value2) {
			addCriterion("user_icon between", value1, value2, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserIconNotBetween(String value1, String value2) {
			addCriterion("user_icon not between", value1, value2, "userIcon");
			return (Criteria) this;
		}

		public Criteria andUserRealnameIsNull() {
			addCriterion("user_realname is null");
			return (Criteria) this;
		}

		public Criteria andUserRealnameIsNotNull() {
			addCriterion("user_realname is not null");
			return (Criteria) this;
		}

		public Criteria andUserRealnameEqualTo(String value) {
			addCriterion("user_realname =", value, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameNotEqualTo(String value) {
			addCriterion("user_realname <>", value, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameGreaterThan(String value) {
			addCriterion("user_realname >", value, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameGreaterThanOrEqualTo(String value) {
			addCriterion("user_realname >=", value, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameLessThan(String value) {
			addCriterion("user_realname <", value, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameLessThanOrEqualTo(String value) {
			addCriterion("user_realname <=", value, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameLike(String value) {
			addCriterion("user_realname like", value, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameNotLike(String value) {
			addCriterion("user_realname not like", value, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameIn(List<String> values) {
			addCriterion("user_realname in", values, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameNotIn(List<String> values) {
			addCriterion("user_realname not in", values, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameBetween(String value1, String value2) {
			addCriterion("user_realname between", value1, value2, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserRealnameNotBetween(String value1, String value2) {
			addCriterion("user_realname not between", value1, value2, "userRealname");
			return (Criteria) this;
		}

		public Criteria andUserIdcardIsNull() {
			addCriterion("user_idCard is null");
			return (Criteria) this;
		}

		public Criteria andUserIdcardIsNotNull() {
			addCriterion("user_idCard is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdcardEqualTo(String value) {
			addCriterion("user_idCard =", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardNotEqualTo(String value) {
			addCriterion("user_idCard <>", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardGreaterThan(String value) {
			addCriterion("user_idCard >", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardGreaterThanOrEqualTo(String value) {
			addCriterion("user_idCard >=", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardLessThan(String value) {
			addCriterion("user_idCard <", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardLessThanOrEqualTo(String value) {
			addCriterion("user_idCard <=", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardLike(String value) {
			addCriterion("user_idCard like", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardNotLike(String value) {
			addCriterion("user_idCard not like", value, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardIn(List<String> values) {
			addCriterion("user_idCard in", values, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardNotIn(List<String> values) {
			addCriterion("user_idCard not in", values, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardBetween(String value1, String value2) {
			addCriterion("user_idCard between", value1, value2, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserIdcardNotBetween(String value1, String value2) {
			addCriterion("user_idCard not between", value1, value2, "userIdcard");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIsNull() {
			addCriterion("user_phone is null");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIsNotNull() {
			addCriterion("user_phone is not null");
			return (Criteria) this;
		}

		public Criteria andUserPhoneEqualTo(String value) {
			addCriterion("user_phone =", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotEqualTo(String value) {
			addCriterion("user_phone <>", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneGreaterThan(String value) {
			addCriterion("user_phone >", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("user_phone >=", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLessThan(String value) {
			addCriterion("user_phone <", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLessThanOrEqualTo(String value) {
			addCriterion("user_phone <=", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneLike(String value) {
			addCriterion("user_phone like", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotLike(String value) {
			addCriterion("user_phone not like", value, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneIn(List<String> values) {
			addCriterion("user_phone in", values, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotIn(List<String> values) {
			addCriterion("user_phone not in", values, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneBetween(String value1, String value2) {
			addCriterion("user_phone between", value1, value2, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserPhoneNotBetween(String value1, String value2) {
			addCriterion("user_phone not between", value1, value2, "userPhone");
			return (Criteria) this;
		}

		public Criteria andUserMailIsNull() {
			addCriterion("user_mail is null");
			return (Criteria) this;
		}

		public Criteria andUserMailIsNotNull() {
			addCriterion("user_mail is not null");
			return (Criteria) this;
		}

		public Criteria andUserMailEqualTo(String value) {
			addCriterion("user_mail =", value, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailNotEqualTo(String value) {
			addCriterion("user_mail <>", value, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailGreaterThan(String value) {
			addCriterion("user_mail >", value, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailGreaterThanOrEqualTo(String value) {
			addCriterion("user_mail >=", value, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailLessThan(String value) {
			addCriterion("user_mail <", value, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailLessThanOrEqualTo(String value) {
			addCriterion("user_mail <=", value, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailLike(String value) {
			addCriterion("user_mail like", value, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailNotLike(String value) {
			addCriterion("user_mail not like", value, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailIn(List<String> values) {
			addCriterion("user_mail in", values, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailNotIn(List<String> values) {
			addCriterion("user_mail not in", values, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailBetween(String value1, String value2) {
			addCriterion("user_mail between", value1, value2, "userMail");
			return (Criteria) this;
		}

		public Criteria andUserMailNotBetween(String value1, String value2) {
			addCriterion("user_mail not between", value1, value2, "userMail");
			return (Criteria) this;
		}

		public Criteria andFavorCntIsNull() {
			addCriterion("favor_cnt is null");
			return (Criteria) this;
		}

		public Criteria andFavorCntIsNotNull() {
			addCriterion("favor_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andFavorCntEqualTo(Integer value) {
			addCriterion("favor_cnt =", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntNotEqualTo(Integer value) {
			addCriterion("favor_cnt <>", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntGreaterThan(Integer value) {
			addCriterion("favor_cnt >", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("favor_cnt >=", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntLessThan(Integer value) {
			addCriterion("favor_cnt <", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntLessThanOrEqualTo(Integer value) {
			addCriterion("favor_cnt <=", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntIn(List<Integer> values) {
			addCriterion("favor_cnt in", values, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntNotIn(List<Integer> values) {
			addCriterion("favor_cnt not in", values, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntBetween(Integer value1, Integer value2) {
			addCriterion("favor_cnt between", value1, value2, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntNotBetween(Integer value1, Integer value2) {
			addCriterion("favor_cnt not between", value1, value2, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntIsNull() {
			addCriterion("coin_cnt is null");
			return (Criteria) this;
		}

		public Criteria andCoinCntIsNotNull() {
			addCriterion("coin_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andCoinCntEqualTo(Integer value) {
			addCriterion("coin_cnt =", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntNotEqualTo(Integer value) {
			addCriterion("coin_cnt <>", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntGreaterThan(Integer value) {
			addCriterion("coin_cnt >", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("coin_cnt >=", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntLessThan(Integer value) {
			addCriterion("coin_cnt <", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntLessThanOrEqualTo(Integer value) {
			addCriterion("coin_cnt <=", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntIn(List<Integer> values) {
			addCriterion("coin_cnt in", values, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntNotIn(List<Integer> values) {
			addCriterion("coin_cnt not in", values, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntBetween(Integer value1, Integer value2) {
			addCriterion("coin_cnt between", value1, value2, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntNotBetween(Integer value1, Integer value2) {
			addCriterion("coin_cnt not between", value1, value2, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinNumIsNull() {
			addCriterion("coin_num is null");
			return (Criteria) this;
		}

		public Criteria andCoinNumIsNotNull() {
			addCriterion("coin_num is not null");
			return (Criteria) this;
		}

		public Criteria andCoinNumEqualTo(Integer value) {
			addCriterion("coin_num =", value, "coinNum");
			return (Criteria) this;
		}

		public Criteria andCoinNumNotEqualTo(Integer value) {
			addCriterion("coin_num <>", value, "coinNum");
			return (Criteria) this;
		}

		public Criteria andCoinNumGreaterThan(Integer value) {
			addCriterion("coin_num >", value, "coinNum");
			return (Criteria) this;
		}

		public Criteria andCoinNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("coin_num >=", value, "coinNum");
			return (Criteria) this;
		}

		public Criteria andCoinNumLessThan(Integer value) {
			addCriterion("coin_num <", value, "coinNum");
			return (Criteria) this;
		}

		public Criteria andCoinNumLessThanOrEqualTo(Integer value) {
			addCriterion("coin_num <=", value, "coinNum");
			return (Criteria) this;
		}

		public Criteria andCoinNumIn(List<Integer> values) {
			addCriterion("coin_num in", values, "coinNum");
			return (Criteria) this;
		}

		public Criteria andCoinNumNotIn(List<Integer> values) {
			addCriterion("coin_num not in", values, "coinNum");
			return (Criteria) this;
		}

		public Criteria andCoinNumBetween(Integer value1, Integer value2) {
			addCriterion("coin_num between", value1, value2, "coinNum");
			return (Criteria) this;
		}

		public Criteria andCoinNumNotBetween(Integer value1, Integer value2) {
			addCriterion("coin_num not between", value1, value2, "coinNum");
			return (Criteria) this;
		}

		public Criteria andPraiseCntIsNull() {
			addCriterion("praise_cnt is null");
			return (Criteria) this;
		}

		public Criteria andPraiseCntIsNotNull() {
			addCriterion("praise_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andPraiseCntEqualTo(Integer value) {
			addCriterion("praise_cnt =", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntNotEqualTo(Integer value) {
			addCriterion("praise_cnt <>", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntGreaterThan(Integer value) {
			addCriterion("praise_cnt >", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("praise_cnt >=", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntLessThan(Integer value) {
			addCriterion("praise_cnt <", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntLessThanOrEqualTo(Integer value) {
			addCriterion("praise_cnt <=", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntIn(List<Integer> values) {
			addCriterion("praise_cnt in", values, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntNotIn(List<Integer> values) {
			addCriterion("praise_cnt not in", values, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntBetween(Integer value1, Integer value2) {
			addCriterion("praise_cnt between", value1, value2, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntNotBetween(Integer value1, Integer value2) {
			addCriterion("praise_cnt not between", value1, value2, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntIsNull() {
			addCriterion("negative_cnt is null");
			return (Criteria) this;
		}

		public Criteria andNegativeCntIsNotNull() {
			addCriterion("negative_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andNegativeCntEqualTo(Integer value) {
			addCriterion("negative_cnt =", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntNotEqualTo(Integer value) {
			addCriterion("negative_cnt <>", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntGreaterThan(Integer value) {
			addCriterion("negative_cnt >", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("negative_cnt >=", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntLessThan(Integer value) {
			addCriterion("negative_cnt <", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntLessThanOrEqualTo(Integer value) {
			addCriterion("negative_cnt <=", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntIn(List<Integer> values) {
			addCriterion("negative_cnt in", values, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntNotIn(List<Integer> values) {
			addCriterion("negative_cnt not in", values, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntBetween(Integer value1, Integer value2) {
			addCriterion("negative_cnt between", value1, value2, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntNotBetween(Integer value1, Integer value2) {
			addCriterion("negative_cnt not between", value1, value2, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntIsNull() {
			addCriterion("avg_cnt is null");
			return (Criteria) this;
		}

		public Criteria andAvgCntIsNotNull() {
			addCriterion("avg_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andAvgCntEqualTo(Integer value) {
			addCriterion("avg_cnt =", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntNotEqualTo(Integer value) {
			addCriterion("avg_cnt <>", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntGreaterThan(Integer value) {
			addCriterion("avg_cnt >", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("avg_cnt >=", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntLessThan(Integer value) {
			addCriterion("avg_cnt <", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntLessThanOrEqualTo(Integer value) {
			addCriterion("avg_cnt <=", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntIn(List<Integer> values) {
			addCriterion("avg_cnt in", values, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntNotIn(List<Integer> values) {
			addCriterion("avg_cnt not in", values, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntBetween(Integer value1, Integer value2) {
			addCriterion("avg_cnt between", value1, value2, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntNotBetween(Integer value1, Integer value2) {
			addCriterion("avg_cnt not between", value1, value2, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntIsNull() {
			addCriterion("effect_cnt is null");
			return (Criteria) this;
		}

		public Criteria andEffectCntIsNotNull() {
			addCriterion("effect_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andEffectCntEqualTo(Integer value) {
			addCriterion("effect_cnt =", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntNotEqualTo(Integer value) {
			addCriterion("effect_cnt <>", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntGreaterThan(Integer value) {
			addCriterion("effect_cnt >", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("effect_cnt >=", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntLessThan(Integer value) {
			addCriterion("effect_cnt <", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntLessThanOrEqualTo(Integer value) {
			addCriterion("effect_cnt <=", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntIn(List<Integer> values) {
			addCriterion("effect_cnt in", values, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntNotIn(List<Integer> values) {
			addCriterion("effect_cnt not in", values, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntBetween(Integer value1, Integer value2) {
			addCriterion("effect_cnt between", value1, value2, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntNotBetween(Integer value1, Integer value2) {
			addCriterion("effect_cnt not between", value1, value2, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorIsNull() {
			addCriterion("personal_honor is null");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorIsNotNull() {
			addCriterion("personal_honor is not null");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorEqualTo(String value) {
			addCriterion("personal_honor =", value, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorNotEqualTo(String value) {
			addCriterion("personal_honor <>", value, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorGreaterThan(String value) {
			addCriterion("personal_honor >", value, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorGreaterThanOrEqualTo(String value) {
			addCriterion("personal_honor >=", value, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorLessThan(String value) {
			addCriterion("personal_honor <", value, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorLessThanOrEqualTo(String value) {
			addCriterion("personal_honor <=", value, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorLike(String value) {
			addCriterion("personal_honor like", value, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorNotLike(String value) {
			addCriterion("personal_honor not like", value, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorIn(List<String> values) {
			addCriterion("personal_honor in", values, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorNotIn(List<String> values) {
			addCriterion("personal_honor not in", values, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorBetween(String value1, String value2) {
			addCriterion("personal_honor between", value1, value2, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andPersonalHonorNotBetween(String value1, String value2) {
			addCriterion("personal_honor not between", value1, value2, "personalHonor");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeIsNull() {
			addCriterion("user_last_time is null");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeIsNotNull() {
			addCriterion("user_last_time is not null");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeEqualTo(Date value) {
			addCriterion("user_last_time =", value, "userLastTime");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeNotEqualTo(Date value) {
			addCriterion("user_last_time <>", value, "userLastTime");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeGreaterThan(Date value) {
			addCriterion("user_last_time >", value, "userLastTime");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("user_last_time >=", value, "userLastTime");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeLessThan(Date value) {
			addCriterion("user_last_time <", value, "userLastTime");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeLessThanOrEqualTo(Date value) {
			addCriterion("user_last_time <=", value, "userLastTime");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeIn(List<Date> values) {
			addCriterion("user_last_time in", values, "userLastTime");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeNotIn(List<Date> values) {
			addCriterion("user_last_time not in", values, "userLastTime");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeBetween(Date value1, Date value2) {
			addCriterion("user_last_time between", value1, value2, "userLastTime");
			return (Criteria) this;
		}

		public Criteria andUserLastTimeNotBetween(Date value1, Date value2) {
			addCriterion("user_last_time not between", value1, value2, "userLastTime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Date value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Date value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Date value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Date value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Date value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Date> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Date> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Date value1, Date value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Date value1, Date value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("updatetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("updatetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("updatetime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("updatetime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("updatetime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("updatetime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("updatetime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("updatetime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("updatetime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("updatetime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("updatetime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("updatetime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andDeltimeIsNull() {
			addCriterion("deltime is null");
			return (Criteria) this;
		}

		public Criteria andDeltimeIsNotNull() {
			addCriterion("deltime is not null");
			return (Criteria) this;
		}

		public Criteria andDeltimeEqualTo(Integer value) {
			addCriterion("deltime =", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeNotEqualTo(Integer value) {
			addCriterion("deltime <>", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeGreaterThan(Integer value) {
			addCriterion("deltime >", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("deltime >=", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeLessThan(Integer value) {
			addCriterion("deltime <", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeLessThanOrEqualTo(Integer value) {
			addCriterion("deltime <=", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeIn(List<Integer> values) {
			addCriterion("deltime in", values, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeNotIn(List<Integer> values) {
			addCriterion("deltime not in", values, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeBetween(Integer value1, Integer value2) {
			addCriterion("deltime between", value1, value2, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeNotBetween(Integer value1, Integer value2) {
			addCriterion("deltime not between", value1, value2, "deltime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table almn_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table almn_user
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 21 17:00:47 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}