package demo.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table almn_role
 */
public class AlmnRole extends BaseModel {

	/**
	 * 角色名称
	 * @ColumnNamerole_name
	 * @mbg.generated   2021-05-12 16:22:25
	 */
	private String roleName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_role.role_name
	 * @return  the value of almn_role.role_name
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_role.role_name
	 * @param roleName  the value for almn_role.role_name
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}
}