package demo.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table almn_role_rule
 */
public class AlmnRoleRule extends BaseModel {
    /**
    *关联的角色
    * @ColumnNamerole_id
    * @mbg.generated  2021-04-21 17:00:47
    */
    private Integer roleId;

    /**
    *关联的导航
    * @ColumnNamenav_id
    * @mbg.generated  2021-04-21 17:00:47
    */
    private Integer navId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_role_rule.role_id
     *
     * @return the value of almn_role_rule.role_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_role_rule.role_id
     *
     * @param roleId the value for almn_role_rule.role_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_role_rule.nav_id
     *
     * @return the value of almn_role_rule.nav_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public Integer getNavId() {
        return navId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_role_rule.nav_id
     *
     * @param navId the value for almn_role_rule.nav_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setNavId(Integer navId) {
        this.navId = navId;
    }
}