package demo.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AlmnDailyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public AlmnDailyExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andDailyIdIsNull() {
			addCriterion("daily_id is null");
			return (Criteria) this;
		}

		public Criteria andDailyIdIsNotNull() {
			addCriterion("daily_id is not null");
			return (Criteria) this;
		}

		public Criteria andDailyIdEqualTo(String value) {
			addCriterion("daily_id =", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdNotEqualTo(String value) {
			addCriterion("daily_id <>", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdGreaterThan(String value) {
			addCriterion("daily_id >", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdGreaterThanOrEqualTo(String value) {
			addCriterion("daily_id >=", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdLessThan(String value) {
			addCriterion("daily_id <", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdLessThanOrEqualTo(String value) {
			addCriterion("daily_id <=", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdLike(String value) {
			addCriterion("daily_id like", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdNotLike(String value) {
			addCriterion("daily_id not like", value, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdIn(List<String> values) {
			addCriterion("daily_id in", values, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdNotIn(List<String> values) {
			addCriterion("daily_id not in", values, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdBetween(String value1, String value2) {
			addCriterion("daily_id between", value1, value2, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyIdNotBetween(String value1, String value2) {
			addCriterion("daily_id not between", value1, value2, "dailyId");
			return (Criteria) this;
		}

		public Criteria andDailyTag1IsNull() {
			addCriterion("daily_tag1 is null");
			return (Criteria) this;
		}

		public Criteria andDailyTag1IsNotNull() {
			addCriterion("daily_tag1 is not null");
			return (Criteria) this;
		}

		public Criteria andDailyTag1EqualTo(String value) {
			addCriterion("daily_tag1 =", value, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1NotEqualTo(String value) {
			addCriterion("daily_tag1 <>", value, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1GreaterThan(String value) {
			addCriterion("daily_tag1 >", value, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1GreaterThanOrEqualTo(String value) {
			addCriterion("daily_tag1 >=", value, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1LessThan(String value) {
			addCriterion("daily_tag1 <", value, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1LessThanOrEqualTo(String value) {
			addCriterion("daily_tag1 <=", value, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1Like(String value) {
			addCriterion("daily_tag1 like", value, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1NotLike(String value) {
			addCriterion("daily_tag1 not like", value, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1In(List<String> values) {
			addCriterion("daily_tag1 in", values, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1NotIn(List<String> values) {
			addCriterion("daily_tag1 not in", values, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1Between(String value1, String value2) {
			addCriterion("daily_tag1 between", value1, value2, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag1NotBetween(String value1, String value2) {
			addCriterion("daily_tag1 not between", value1, value2, "dailyTag1");
			return (Criteria) this;
		}

		public Criteria andDailyTag2IsNull() {
			addCriterion("daily_tag2 is null");
			return (Criteria) this;
		}

		public Criteria andDailyTag2IsNotNull() {
			addCriterion("daily_tag2 is not null");
			return (Criteria) this;
		}

		public Criteria andDailyTag2EqualTo(String value) {
			addCriterion("daily_tag2 =", value, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2NotEqualTo(String value) {
			addCriterion("daily_tag2 <>", value, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2GreaterThan(String value) {
			addCriterion("daily_tag2 >", value, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2GreaterThanOrEqualTo(String value) {
			addCriterion("daily_tag2 >=", value, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2LessThan(String value) {
			addCriterion("daily_tag2 <", value, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2LessThanOrEqualTo(String value) {
			addCriterion("daily_tag2 <=", value, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2Like(String value) {
			addCriterion("daily_tag2 like", value, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2NotLike(String value) {
			addCriterion("daily_tag2 not like", value, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2In(List<String> values) {
			addCriterion("daily_tag2 in", values, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2NotIn(List<String> values) {
			addCriterion("daily_tag2 not in", values, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2Between(String value1, String value2) {
			addCriterion("daily_tag2 between", value1, value2, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyTag2NotBetween(String value1, String value2) {
			addCriterion("daily_tag2 not between", value1, value2, "dailyTag2");
			return (Criteria) this;
		}

		public Criteria andDailyContentIsNull() {
			addCriterion("daily_content is null");
			return (Criteria) this;
		}

		public Criteria andDailyContentIsNotNull() {
			addCriterion("daily_content is not null");
			return (Criteria) this;
		}

		public Criteria andDailyContentEqualTo(String value) {
			addCriterion("daily_content =", value, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentNotEqualTo(String value) {
			addCriterion("daily_content <>", value, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentGreaterThan(String value) {
			addCriterion("daily_content >", value, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentGreaterThanOrEqualTo(String value) {
			addCriterion("daily_content >=", value, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentLessThan(String value) {
			addCriterion("daily_content <", value, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentLessThanOrEqualTo(String value) {
			addCriterion("daily_content <=", value, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentLike(String value) {
			addCriterion("daily_content like", value, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentNotLike(String value) {
			addCriterion("daily_content not like", value, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentIn(List<String> values) {
			addCriterion("daily_content in", values, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentNotIn(List<String> values) {
			addCriterion("daily_content not in", values, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentBetween(String value1, String value2) {
			addCriterion("daily_content between", value1, value2, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyContentNotBetween(String value1, String value2) {
			addCriterion("daily_content not between", value1, value2, "dailyContent");
			return (Criteria) this;
		}

		public Criteria andDailyImgListIsNull() {
			addCriterion("daily_img_list is null");
			return (Criteria) this;
		}

		public Criteria andDailyImgListIsNotNull() {
			addCriterion("daily_img_list is not null");
			return (Criteria) this;
		}

		public Criteria andDailyImgListEqualTo(String value) {
			addCriterion("daily_img_list =", value, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListNotEqualTo(String value) {
			addCriterion("daily_img_list <>", value, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListGreaterThan(String value) {
			addCriterion("daily_img_list >", value, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListGreaterThanOrEqualTo(String value) {
			addCriterion("daily_img_list >=", value, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListLessThan(String value) {
			addCriterion("daily_img_list <", value, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListLessThanOrEqualTo(String value) {
			addCriterion("daily_img_list <=", value, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListLike(String value) {
			addCriterion("daily_img_list like", value, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListNotLike(String value) {
			addCriterion("daily_img_list not like", value, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListIn(List<String> values) {
			addCriterion("daily_img_list in", values, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListNotIn(List<String> values) {
			addCriterion("daily_img_list not in", values, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListBetween(String value1, String value2) {
			addCriterion("daily_img_list between", value1, value2, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andDailyImgListNotBetween(String value1, String value2) {
			addCriterion("daily_img_list not between", value1, value2, "dailyImgList");
			return (Criteria) this;
		}

		public Criteria andFavorCntIsNull() {
			addCriterion("favor_cnt is null");
			return (Criteria) this;
		}

		public Criteria andFavorCntIsNotNull() {
			addCriterion("favor_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andFavorCntEqualTo(Integer value) {
			addCriterion("favor_cnt =", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntNotEqualTo(Integer value) {
			addCriterion("favor_cnt <>", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntGreaterThan(Integer value) {
			addCriterion("favor_cnt >", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("favor_cnt >=", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntLessThan(Integer value) {
			addCriterion("favor_cnt <", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntLessThanOrEqualTo(Integer value) {
			addCriterion("favor_cnt <=", value, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntIn(List<Integer> values) {
			addCriterion("favor_cnt in", values, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntNotIn(List<Integer> values) {
			addCriterion("favor_cnt not in", values, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntBetween(Integer value1, Integer value2) {
			addCriterion("favor_cnt between", value1, value2, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andFavorCntNotBetween(Integer value1, Integer value2) {
			addCriterion("favor_cnt not between", value1, value2, "favorCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntIsNull() {
			addCriterion("coin_cnt is null");
			return (Criteria) this;
		}

		public Criteria andCoinCntIsNotNull() {
			addCriterion("coin_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andCoinCntEqualTo(Integer value) {
			addCriterion("coin_cnt =", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntNotEqualTo(Integer value) {
			addCriterion("coin_cnt <>", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntGreaterThan(Integer value) {
			addCriterion("coin_cnt >", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("coin_cnt >=", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntLessThan(Integer value) {
			addCriterion("coin_cnt <", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntLessThanOrEqualTo(Integer value) {
			addCriterion("coin_cnt <=", value, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntIn(List<Integer> values) {
			addCriterion("coin_cnt in", values, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntNotIn(List<Integer> values) {
			addCriterion("coin_cnt not in", values, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntBetween(Integer value1, Integer value2) {
			addCriterion("coin_cnt between", value1, value2, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andCoinCntNotBetween(Integer value1, Integer value2) {
			addCriterion("coin_cnt not between", value1, value2, "coinCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntIsNull() {
			addCriterion("praise_cnt is null");
			return (Criteria) this;
		}

		public Criteria andPraiseCntIsNotNull() {
			addCriterion("praise_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andPraiseCntEqualTo(Integer value) {
			addCriterion("praise_cnt =", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntNotEqualTo(Integer value) {
			addCriterion("praise_cnt <>", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntGreaterThan(Integer value) {
			addCriterion("praise_cnt >", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("praise_cnt >=", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntLessThan(Integer value) {
			addCriterion("praise_cnt <", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntLessThanOrEqualTo(Integer value) {
			addCriterion("praise_cnt <=", value, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntIn(List<Integer> values) {
			addCriterion("praise_cnt in", values, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntNotIn(List<Integer> values) {
			addCriterion("praise_cnt not in", values, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntBetween(Integer value1, Integer value2) {
			addCriterion("praise_cnt between", value1, value2, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andPraiseCntNotBetween(Integer value1, Integer value2) {
			addCriterion("praise_cnt not between", value1, value2, "praiseCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntIsNull() {
			addCriterion("negative_cnt is null");
			return (Criteria) this;
		}

		public Criteria andNegativeCntIsNotNull() {
			addCriterion("negative_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andNegativeCntEqualTo(Integer value) {
			addCriterion("negative_cnt =", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntNotEqualTo(Integer value) {
			addCriterion("negative_cnt <>", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntGreaterThan(Integer value) {
			addCriterion("negative_cnt >", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("negative_cnt >=", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntLessThan(Integer value) {
			addCriterion("negative_cnt <", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntLessThanOrEqualTo(Integer value) {
			addCriterion("negative_cnt <=", value, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntIn(List<Integer> values) {
			addCriterion("negative_cnt in", values, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntNotIn(List<Integer> values) {
			addCriterion("negative_cnt not in", values, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntBetween(Integer value1, Integer value2) {
			addCriterion("negative_cnt between", value1, value2, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andNegativeCntNotBetween(Integer value1, Integer value2) {
			addCriterion("negative_cnt not between", value1, value2, "negativeCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntIsNull() {
			addCriterion("avg_cnt is null");
			return (Criteria) this;
		}

		public Criteria andAvgCntIsNotNull() {
			addCriterion("avg_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andAvgCntEqualTo(Integer value) {
			addCriterion("avg_cnt =", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntNotEqualTo(Integer value) {
			addCriterion("avg_cnt <>", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntGreaterThan(Integer value) {
			addCriterion("avg_cnt >", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("avg_cnt >=", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntLessThan(Integer value) {
			addCriterion("avg_cnt <", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntLessThanOrEqualTo(Integer value) {
			addCriterion("avg_cnt <=", value, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntIn(List<Integer> values) {
			addCriterion("avg_cnt in", values, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntNotIn(List<Integer> values) {
			addCriterion("avg_cnt not in", values, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntBetween(Integer value1, Integer value2) {
			addCriterion("avg_cnt between", value1, value2, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andAvgCntNotBetween(Integer value1, Integer value2) {
			addCriterion("avg_cnt not between", value1, value2, "avgCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntIsNull() {
			addCriterion("effect_cnt is null");
			return (Criteria) this;
		}

		public Criteria andEffectCntIsNotNull() {
			addCriterion("effect_cnt is not null");
			return (Criteria) this;
		}

		public Criteria andEffectCntEqualTo(Integer value) {
			addCriterion("effect_cnt =", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntNotEqualTo(Integer value) {
			addCriterion("effect_cnt <>", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntGreaterThan(Integer value) {
			addCriterion("effect_cnt >", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntGreaterThanOrEqualTo(Integer value) {
			addCriterion("effect_cnt >=", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntLessThan(Integer value) {
			addCriterion("effect_cnt <", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntLessThanOrEqualTo(Integer value) {
			addCriterion("effect_cnt <=", value, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntIn(List<Integer> values) {
			addCriterion("effect_cnt in", values, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntNotIn(List<Integer> values) {
			addCriterion("effect_cnt not in", values, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntBetween(Integer value1, Integer value2) {
			addCriterion("effect_cnt between", value1, value2, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andEffectCntNotBetween(Integer value1, Integer value2) {
			addCriterion("effect_cnt not between", value1, value2, "effectCnt");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("addtime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("addtime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Date value) {
			addCriterion("addtime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Date value) {
			addCriterion("addtime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Date value) {
			addCriterion("addtime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("addtime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Date value) {
			addCriterion("addtime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Date value) {
			addCriterion("addtime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Date> values) {
			addCriterion("addtime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Date> values) {
			addCriterion("addtime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Date value1, Date value2) {
			addCriterion("addtime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Date value1, Date value2) {
			addCriterion("addtime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("updatetime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("updatetime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("updatetime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("updatetime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("updatetime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("updatetime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("updatetime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("updatetime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("updatetime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("updatetime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("updatetime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("updatetime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andDeltimeIsNull() {
			addCriterion("deltime is null");
			return (Criteria) this;
		}

		public Criteria andDeltimeIsNotNull() {
			addCriterion("deltime is not null");
			return (Criteria) this;
		}

		public Criteria andDeltimeEqualTo(Integer value) {
			addCriterion("deltime =", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeNotEqualTo(Integer value) {
			addCriterion("deltime <>", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeGreaterThan(Integer value) {
			addCriterion("deltime >", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("deltime >=", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeLessThan(Integer value) {
			addCriterion("deltime <", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeLessThanOrEqualTo(Integer value) {
			addCriterion("deltime <=", value, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeIn(List<Integer> values) {
			addCriterion("deltime in", values, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeNotIn(List<Integer> values) {
			addCriterion("deltime not in", values, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeBetween(Integer value1, Integer value2) {
			addCriterion("deltime between", value1, value2, "deltime");
			return (Criteria) this;
		}

		public Criteria andDeltimeNotBetween(Integer value1, Integer value2) {
			addCriterion("deltime not between", value1, value2, "deltime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table almn_daily
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 21 17:00:47 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}