package demo.dao.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table almn_user
 */
public class AlmnUser extends BaseModel {

	/**
	 * 角色ID
	 * @ColumnNamerole_id
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private Integer roleId;
	/**
	 * 登录学号
	 * @ColumnNameuser_id
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private String userId;
	/**
	 * 关注用户
	 * @ColumnNameenjoy_user
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private String enjoyUser;
	/**
	 * 感兴趣标签
	 * @ColumnNameenjoy_tag
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private String enjoyTag;
	/**
	 * 登录密码
	 * @ColumnNameuser_passwd
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private String userPasswd;
	/**
	 * 用户头像
	 * @ColumnNameuser_icon
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private String userIcon;
	/**
	 * 真实姓名
	 * @ColumnNameuser_realname
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private String userRealname;
	/**
	 * 身份证号
	 * @ColumnNameuser_idCard
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private String userIdcard;
	/**
	 * 联系电话
	 * @ColumnNameuser_phone
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private String userPhone;
	/**
	 * 联系邮箱
	 * @ColumnNameuser_mail
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private String userMail;
	/**
	 * 点赞数
	 * @ColumnNamefavor_cnt
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private Integer favorCnt;
	/**
	 * 投币数
	 * @ColumnNamecoin_cnt
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private Integer coinCnt;
	/**
	 * 硬币数
	 * @ColumnNamecoin_num
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private Integer coinNum;
	/**
	 * 好评数
	 * @ColumnNamepraise_cnt
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private Integer praiseCnt;
	/**
	 * 差评数
	 * @ColumnNamenegative_cnt
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private Integer negativeCnt;
	/**
	 * 普通评论数
	 * @ColumnNameavg_cnt
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private Integer avgCnt;
	/**
	 * 热度（影响力）
	 * @ColumnNameeffect_cnt
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private Integer effectCnt;
	/**
	 * 个人荣誉信息
	 * @ColumnNamepersonal_honor
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private String personalHonor;
	/**
	 * 上一次登录的时间
	 * @ColumnNameuser_last_time
	 * @mbg.generated   2021-05-30 20:25:24
	 */
	private Date userLastTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.role_id
	 * @return  the value of almn_user.role_id
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.role_id
	 * @param roleId  the value for almn_user.role_id
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.user_id
	 * @return  the value of almn_user.user_id
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.user_id
	 * @param userId  the value for almn_user.user_id
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.enjoy_user
	 * @return  the value of almn_user.enjoy_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getEnjoyUser() {
		return enjoyUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.enjoy_user
	 * @param enjoyUser  the value for almn_user.enjoy_user
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setEnjoyUser(String enjoyUser) {
		this.enjoyUser = enjoyUser == null ? null : enjoyUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.enjoy_tag
	 * @return  the value of almn_user.enjoy_tag
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getEnjoyTag() {
		return enjoyTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.enjoy_tag
	 * @param enjoyTag  the value for almn_user.enjoy_tag
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setEnjoyTag(String enjoyTag) {
		this.enjoyTag = enjoyTag == null ? null : enjoyTag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.user_passwd
	 * @return  the value of almn_user.user_passwd
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getUserPasswd() {
		return userPasswd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.user_passwd
	 * @param userPasswd  the value for almn_user.user_passwd
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setUserPasswd(String userPasswd) {
		this.userPasswd = userPasswd == null ? null : userPasswd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.user_icon
	 * @return  the value of almn_user.user_icon
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getUserIcon() {
		return userIcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.user_icon
	 * @param userIcon  the value for almn_user.user_icon
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setUserIcon(String userIcon) {
		this.userIcon = userIcon == null ? null : userIcon.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.user_realname
	 * @return  the value of almn_user.user_realname
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getUserRealname() {
		return userRealname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.user_realname
	 * @param userRealname  the value for almn_user.user_realname
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setUserRealname(String userRealname) {
		this.userRealname = userRealname == null ? null : userRealname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.user_idCard
	 * @return  the value of almn_user.user_idCard
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getUserIdcard() {
		return userIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.user_idCard
	 * @param userIdcard  the value for almn_user.user_idCard
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setUserIdcard(String userIdcard) {
		this.userIdcard = userIdcard == null ? null : userIdcard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.user_phone
	 * @return  the value of almn_user.user_phone
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getUserPhone() {
		return userPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.user_phone
	 * @param userPhone  the value for almn_user.user_phone
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone == null ? null : userPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.user_mail
	 * @return  the value of almn_user.user_mail
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getUserMail() {
		return userMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.user_mail
	 * @param userMail  the value for almn_user.user_mail
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setUserMail(String userMail) {
		this.userMail = userMail == null ? null : userMail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.favor_cnt
	 * @return  the value of almn_user.favor_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Integer getFavorCnt() {
		return favorCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.favor_cnt
	 * @param favorCnt  the value for almn_user.favor_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setFavorCnt(Integer favorCnt) {
		this.favorCnt = favorCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.coin_cnt
	 * @return  the value of almn_user.coin_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Integer getCoinCnt() {
		return coinCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.coin_cnt
	 * @param coinCnt  the value for almn_user.coin_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setCoinCnt(Integer coinCnt) {
		this.coinCnt = coinCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.coin_num
	 * @return  the value of almn_user.coin_num
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Integer getCoinNum() {
		return coinNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.coin_num
	 * @param coinNum  the value for almn_user.coin_num
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setCoinNum(Integer coinNum) {
		this.coinNum = coinNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.praise_cnt
	 * @return  the value of almn_user.praise_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Integer getPraiseCnt() {
		return praiseCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.praise_cnt
	 * @param praiseCnt  the value for almn_user.praise_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setPraiseCnt(Integer praiseCnt) {
		this.praiseCnt = praiseCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.negative_cnt
	 * @return  the value of almn_user.negative_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Integer getNegativeCnt() {
		return negativeCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.negative_cnt
	 * @param negativeCnt  the value for almn_user.negative_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setNegativeCnt(Integer negativeCnt) {
		this.negativeCnt = negativeCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.avg_cnt
	 * @return  the value of almn_user.avg_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Integer getAvgCnt() {
		return avgCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.avg_cnt
	 * @param avgCnt  the value for almn_user.avg_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setAvgCnt(Integer avgCnt) {
		this.avgCnt = avgCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.effect_cnt
	 * @return  the value of almn_user.effect_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Integer getEffectCnt() {
		return effectCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.effect_cnt
	 * @param effectCnt  the value for almn_user.effect_cnt
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setEffectCnt(Integer effectCnt) {
		this.effectCnt = effectCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.personal_honor
	 * @return  the value of almn_user.personal_honor
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public String getPersonalHonor() {
		return personalHonor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.personal_honor
	 * @param personalHonor  the value for almn_user.personal_honor
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setPersonalHonor(String personalHonor) {
		this.personalHonor = personalHonor == null ? null : personalHonor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_user.user_last_time
	 * @return  the value of almn_user.user_last_time
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public Date getUserLastTime() {
		return userLastTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_user.user_last_time
	 * @param userLastTime  the value for almn_user.user_last_time
	 * @mbg.generated  Sun May 30 20:25:24 CST 2021
	 */
	public void setUserLastTime(Date userLastTime) {
		this.userLastTime = userLastTime;
	}
}