package demo.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table almn_effect_set
 */
public class AlmnEffectSet extends BaseModel {
    /**
    *热度设置项
    * @ColumnNameeffect_key
    * @mbg.generated  2021-04-21 17:00:47
    */
    private String effectKey;

    /**
    *热度设置值
    * @ColumnNameeffect_val
    * @mbg.generated  2021-04-21 17:00:47
    */
    private Integer effectVal;

    /**
    *备注
    * @ColumnNameeffect_note
    * @mbg.generated  2021-04-21 17:00:47
    */
    private String effectNote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_effect_set.effect_key
     *
     * @return the value of almn_effect_set.effect_key
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public String getEffectKey() {
        return effectKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_effect_set.effect_key
     *
     * @param effectKey the value for almn_effect_set.effect_key
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setEffectKey(String effectKey) {
        this.effectKey = effectKey == null ? null : effectKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_effect_set.effect_val
     *
     * @return the value of almn_effect_set.effect_val
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public Integer getEffectVal() {
        return effectVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_effect_set.effect_val
     *
     * @param effectVal the value for almn_effect_set.effect_val
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setEffectVal(Integer effectVal) {
        this.effectVal = effectVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_effect_set.effect_note
     *
     * @return the value of almn_effect_set.effect_note
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public String getEffectNote() {
        return effectNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_effect_set.effect_note
     *
     * @param effectNote the value for almn_effect_set.effect_note
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setEffectNote(String effectNote) {
        this.effectNote = effectNote == null ? null : effectNote.trim();
    }
}