package demo.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table almn_nav
 */
public class AlmnNav extends BaseModel {

	/**
	 * 父级导航id
	 * @ColumnNameparent_id
	 * @mbg.generated   2021-05-12 16:23:44
	 */
	private Integer parentId;
	/**
	 * 导航名称
	 * @ColumnNamenav_name
	 * @mbg.generated   2021-05-12 16:23:44
	 */
	private String navName;
	/**
	 * 导航跳转链接
	 * @ColumnNamenav_url
	 * @mbg.generated   2021-05-12 16:23:44
	 */
	private String navUrl;
	/**
	 * 导航图标
	 * @ColumnNamenav_icon
	 * @mbg.generated   2021-05-12 16:23:44
	 */
	private String navIcon;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_nav.parent_id
	 * @return  the value of almn_nav.parent_id
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_nav.parent_id
	 * @param parentId  the value for almn_nav.parent_id
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_nav.nav_name
	 * @return  the value of almn_nav.nav_name
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	public String getNavName() {
		return navName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_nav.nav_name
	 * @param navName  the value for almn_nav.nav_name
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	public void setNavName(String navName) {
		this.navName = navName == null ? null : navName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_nav.nav_url
	 * @return  the value of almn_nav.nav_url
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	public String getNavUrl() {
		return navUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_nav.nav_url
	 * @param navUrl  the value for almn_nav.nav_url
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	public void setNavUrl(String navUrl) {
		this.navUrl = navUrl == null ? null : navUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column almn_nav.nav_icon
	 * @return  the value of almn_nav.nav_icon
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	public String getNavIcon() {
		return navIcon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column almn_nav.nav_icon
	 * @param navIcon  the value for almn_nav.nav_icon
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	public void setNavIcon(String navIcon) {
		this.navIcon = navIcon == null ? null : navIcon.trim();
	}
}