package demo.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table almn_info_check
 */
public class AlmnInfoCheck extends BaseModel {
    /**
    *学号
    * @ColumnNameuser_id
    * @mbg.generated  2021-04-21 17:00:47
    */
    private String userId;

    /**
    *真实姓名
    * @ColumnNameuser_realname
    * @mbg.generated  2021-04-21 17:00:47
    */
    private String userRealname;

    /**
    *身份证号
    * @ColumnNameuser_idCard
    * @mbg.generated  2021-04-21 17:00:47
    */
    private String userIdcard;

    /**
    *联系电话
    * @ColumnNameuser_phone
    * @mbg.generated  2021-04-21 17:00:47
    */
    private String userPhone;

    /**
    *联系邮箱
    * @ColumnNameuser_mail
    * @mbg.generated  2021-04-21 17:00:47
    */
    private String userMail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_info_check.user_id
     *
     * @return the value of almn_info_check.user_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_info_check.user_id
     *
     * @param userId the value for almn_info_check.user_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_info_check.user_realname
     *
     * @return the value of almn_info_check.user_realname
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public String getUserRealname() {
        return userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_info_check.user_realname
     *
     * @param userRealname the value for almn_info_check.user_realname
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setUserRealname(String userRealname) {
        this.userRealname = userRealname == null ? null : userRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_info_check.user_idCard
     *
     * @return the value of almn_info_check.user_idCard
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public String getUserIdcard() {
        return userIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_info_check.user_idCard
     *
     * @param userIdcard the value for almn_info_check.user_idCard
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setUserIdcard(String userIdcard) {
        this.userIdcard = userIdcard == null ? null : userIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_info_check.user_phone
     *
     * @return the value of almn_info_check.user_phone
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_info_check.user_phone
     *
     * @param userPhone the value for almn_info_check.user_phone
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_info_check.user_mail
     *
     * @return the value of almn_info_check.user_mail
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_info_check.user_mail
     *
     * @param userMail the value for almn_info_check.user_mail
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail == null ? null : userMail.trim();
    }

	@Override
	public String toString() {
		return "AlmnInfoCheck [userId=" + userId + ", userRealname=" + userRealname + ", userIdcard=" + userIdcard
				+ ", userPhone=" + userPhone + ", userMail=" + userMail + ", toString()=" + super.toString() + "]";
	}
    
    
}