package demo.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table almn_favor_log
 */
public class AlmnFavorLog extends BaseModel {
    /**
    *动态ID
    * @ColumnNamedailys_id
    * @mbg.generated  2021-04-21 17:00:47
    */
    private String dailysId;

    /**
    *被点赞用户学号
    * @ColumnNameuser1_id
    * @mbg.generated  2021-04-21 17:00:47
    */
    private String user1Id;

    /**
    *点赞用户学号
    * @ColumnNameuser2_id
    * @mbg.generated  2021-04-21 17:00:47
    */
    private String user2Id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_favor_log.dailys_id
     *
     * @return the value of almn_favor_log.dailys_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public String getDailysId() {
        return dailysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_favor_log.dailys_id
     *
     * @param dailysId the value for almn_favor_log.dailys_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setDailysId(String dailysId) {
        this.dailysId = dailysId == null ? null : dailysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_favor_log.user1_id
     *
     * @return the value of almn_favor_log.user1_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public String getUser1Id() {
        return user1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_favor_log.user1_id
     *
     * @param user1Id the value for almn_favor_log.user1_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setUser1Id(String user1Id) {
        this.user1Id = user1Id == null ? null : user1Id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column almn_favor_log.user2_id
     *
     * @return the value of almn_favor_log.user2_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public String getUser2Id() {
        return user2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column almn_favor_log.user2_id
     *
     * @param user2Id the value for almn_favor_log.user2_id
     *
     * @mbg.generated Wed Apr 21 17:00:47 CST 2021
     */
    public void setUser2Id(String user2Id) {
        this.user2Id = user2Id == null ? null : user2Id.trim();
    }

	@Override
	public String toString() {
		return "AlmnFavorLog [dailysId=" + dailysId + ", user1Id=" + user1Id + ", user2Id=" + user2Id + ", toString()="
				+ super.toString() + "]";
	}
    
}