package demo.dao.mapper;

import demo.dao.model.AlmnRole;
import demo.dao.model.AlmnRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlmnRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	long countByExample(AlmnRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	int deleteByExample(AlmnRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	int insert(AlmnRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	int insertSelective(AlmnRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	List<AlmnRole> selectByExample(AlmnRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	AlmnRole selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	int updateByExampleSelective(@Param("record") AlmnRole record, @Param("example") AlmnRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	int updateByExample(@Param("record") AlmnRole record, @Param("example") AlmnRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	int updateByPrimaryKeySelective(AlmnRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role
	 * @mbg.generated  Wed May 12 16:22:25 CST 2021
	 */
	int updateByPrimaryKey(AlmnRole record);

	void updateRoleInfo(AlmnRole role);

}