package demo.dao.mapper;

import java.util.List;

import demo.dao.model.AlmnDaily;
import demo.dao.model.AlmnDailyExample;
import org.apache.ibatis.annotations.Param;

public interface AlmnDailyMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	long countByExample(AlmnDailyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	int deleteByExample(AlmnDailyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	int insert(AlmnDaily record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	int insertSelective(AlmnDaily record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	List<AlmnDaily> selectByExample(AlmnDailyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	AlmnDaily selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	int updateByExampleSelective(@Param("record") AlmnDaily record, @Param("example") AlmnDailyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	int updateByExample(@Param("record") AlmnDaily record, @Param("example") AlmnDailyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	int updateByPrimaryKeySelective(AlmnDaily record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_daily
	 * @mbg.generated  Sun May 30 11:06:56 CST 2021
	 */
	int updateByPrimaryKey(AlmnDaily record);
	
	void insertbymy(AlmnDaily daily);
	
	void updateDailyEffect();
	
	List<AlmnDaily> gethotDailyList();
	
}
