package demo.dao.mapper;

import java.util.List;

import demo.dao.model.AlmnEffectSet;
import demo.dao.model.AlmnEffectSetExample;
import org.apache.ibatis.annotations.Param;

public interface AlmnEffectSetMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	long countByExample(AlmnEffectSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int deleteByExample(AlmnEffectSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int insert(AlmnEffectSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int insertSelective(AlmnEffectSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	List<AlmnEffectSet> selectByExample(AlmnEffectSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	AlmnEffectSet selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByExampleSelective(@Param("record") AlmnEffectSet record, @Param("example") AlmnEffectSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByExample(@Param("record") AlmnEffectSet record, @Param("example") AlmnEffectSetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByPrimaryKeySelective(AlmnEffectSet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_effect_set
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByPrimaryKey(AlmnEffectSet record);

	AlmnEffectSet findEffectSetByPrimaryKey(Integer id);
	
	AlmnEffectSet findEffectSetByKey(String key);
	
	List<AlmnEffectSet> selectAllEffectSet();
	
}
