package demo.dao.mapper;

import demo.dao.model.AlmnCoinLog;
import demo.dao.model.AlmnCoinLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlmnCoinLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	long countByExample(AlmnCoinLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int deleteByExample(AlmnCoinLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int insert(AlmnCoinLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int insertSelective(AlmnCoinLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	List<AlmnCoinLog> selectByExample(AlmnCoinLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	AlmnCoinLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByExampleSelective(@Param("record") AlmnCoinLog record, @Param("example") AlmnCoinLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByExample(@Param("record") AlmnCoinLog record, @Param("example") AlmnCoinLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByPrimaryKeySelective(AlmnCoinLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_coin_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByPrimaryKey(AlmnCoinLog record);
}