package demo.dao.mapper;

import java.util.List;

import demo.dao.model.AlmnNav;
import demo.dao.model.AlmnNavExample;
import org.apache.ibatis.annotations.Param;

public interface AlmnNavMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	long countByExample(AlmnNavExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	int deleteByExample(AlmnNavExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	int insert(AlmnNav record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	int insertSelective(AlmnNav record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	List<AlmnNav> selectByExample(AlmnNavExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	AlmnNav selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	int updateByExampleSelective(@Param("record") AlmnNav record, @Param("example") AlmnNavExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	int updateByExample(@Param("record") AlmnNav record, @Param("example") AlmnNavExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	int updateByPrimaryKeySelective(AlmnNav record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_nav
	 * @mbg.generated  Wed May 12 16:23:44 CST 2021
	 */
	int updateByPrimaryKey(AlmnNav record);

	List<AlmnNav> selectNavList();

	List<AlmnNav> selectChildNavList(Integer parent_id);
	
}
