package demo.dao.mapper;

import demo.dao.model.AlmnRoleRule;
import demo.dao.model.AlmnRoleRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlmnRoleRuleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	long countByExample(AlmnRoleRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int deleteByExample(AlmnRoleRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int insert(AlmnRoleRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int insertSelective(AlmnRoleRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	List<AlmnRoleRule> selectByExample(AlmnRoleRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	AlmnRoleRule selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByExampleSelective(@Param("record") AlmnRoleRule record, @Param("example") AlmnRoleRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByExample(@Param("record") AlmnRoleRule record, @Param("example") AlmnRoleRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByPrimaryKeySelective(AlmnRoleRule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_role_rule
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByPrimaryKey(AlmnRoleRule record);
}