package demo.dao.mapper;

import demo.dao.model.AlmnUserRecycle;
import demo.dao.model.AlmnUserRecycleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlmnUserRecycleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	long countByExample(AlmnUserRecycleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int deleteByExample(AlmnUserRecycleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int insert(AlmnUserRecycle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int insertSelective(AlmnUserRecycle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	List<AlmnUserRecycle> selectByExample(AlmnUserRecycleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	AlmnUserRecycle selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByExampleSelective(@Param("record") AlmnUserRecycle record,
			@Param("example") AlmnUserRecycleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByExample(@Param("record") AlmnUserRecycle record, @Param("example") AlmnUserRecycleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByPrimaryKeySelective(AlmnUserRecycle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_user_recycle
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByPrimaryKey(AlmnUserRecycle record);
}