package demo.dao.mapper;

import demo.dao.model.AlmnFavorLog;
import demo.dao.model.AlmnFavorLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlmnFavorLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	long countByExample(AlmnFavorLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int deleteByExample(AlmnFavorLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int insert(AlmnFavorLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int insertSelective(AlmnFavorLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	List<AlmnFavorLog> selectByExample(AlmnFavorLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	AlmnFavorLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByExampleSelective(@Param("record") AlmnFavorLog record, @Param("example") AlmnFavorLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByExample(@Param("record") AlmnFavorLog record, @Param("example") AlmnFavorLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByPrimaryKeySelective(AlmnFavorLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_favor_log
	 * @mbg.generated  Wed Apr 21 17:00:47 CST 2021
	 */
	int updateByPrimaryKey(AlmnFavorLog record);
}