package demo.dao.mapper;

import demo.dao.model.AlmnComment;
import demo.dao.model.AlmnCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlmnCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	long countByExample(AlmnCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	int deleteByExample(AlmnCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	int insert(AlmnComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	int insertSelective(AlmnComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	List<AlmnComment> selectByExample(AlmnCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	AlmnComment selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	int updateByExampleSelective(@Param("record") AlmnComment record, @Param("example") AlmnCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	int updateByExample(@Param("record") AlmnComment record, @Param("example") AlmnCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	int updateByPrimaryKeySelective(AlmnComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table almn_comment
	 * @mbg.generated  Thu Apr 22 13:25:30 CST 2021
	 */
	int updateByPrimaryKey(AlmnComment record);
}