server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/space?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

jwt:
  secret: 49vvw+FXTHDUF/72wY1bZEI/af0lRvko92Q6zlzrrSH6kNDFvx0OU59RsIz4W+WKqFFLb4SwDW/VJL65uQPVJA==
  expiration: 3600000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.space.model

#debug: true
logging:
  level:
    root: INFO
#  file:
#    name: ./src/main/resources/app.log
